version: '3'
services:
  go-app:
    build:
      context: ./go-server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - internal-network

  rust-app:
    build:
      context: ./web_server/rust-server
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    volumes:
      - ./web_server/rust-server:/home/app    
    networks:
      - internal-network

  frontend-app:
    build:
      context: ./web_client
      dockerfile: Dockerfile
    volumes:
      - ./web_client/domesticapp:/home/app  
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development  
    networks:
      - internal-network    

networks:
  internal-network: